# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: MetricsDemo
  profiles:
    active: #spring.profiles.active#

server:
  port: 8081

logging:
  level:
    com.cargowhale: #logback.loglevel#

endpoints:
  metrics:
    filter:
      gauge-submissions: per_http_method
      counter-submissions: per_http_method


# ===================================================================
# CargoWhale specific properties
# ===================================================================
