version: '2'
services:
  cargowhale:
    image: rxnctrllabs/cargo-whale
    external_links:
      - graphite:graphite
    ports:
      - 8081:8081

  grafana:
    image: grafana/grafana
    external_links:
      - graphite:graphite
    ports:
      - 8083:3000

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - 8082:80

