version: '2'
services:
  cargowhale:
    image: cargo-whale-docker
    external_links:
      - socat-docker:socat
      - graphite:graphite
    ports:
      - 8081:8081

  socat-docker:
    extends:
      file: socat.yml
      service: socat-docker

  grafana:
    image: grafana/grafana
    external_links:
      - graphite:graphite
    ports:
      - 8083:3000

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - 8082:80

