version: '2'
services:
  metrics:
    image: rxnctrllabs/pluggedin-metrics
    external_links:
      - graphite:graphite
    ports:
      - 8081:8081

  grafana:
    image: rxnctrllabs/pluggedin-metrics-grafana
    external_links:
      - graphite:graphite
    ports:
      - 8083:3000

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - 8082:80

